export const mockVideos = [
  {
    id: 1,
    title: 'Amazing Tech Review 2024 - Latest Gadgets You Need to See',
    thumbnail: 'Modern tech gadgets on a sleek desk with RGB lighting',
    channelName: 'Tech Insights',
    channelId: 1,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel1',
    views: '1.2M views',
    uploaded: '2 days ago',
    duration: '12:34',
  },
  {
    id: 2,
    title: 'Cooking Tutorial: Perfect Homemade Pizza in 30 Minutes',
    thumbnail: 'Delicious homemade pizza with fresh ingredients',
    channelName: 'Chef Master',
    channelId: 2,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel2',
    views: '536k views',
    uploaded: '1 week ago',
    duration: '15:22',
  },
  {
    id: 3,
    title: 'Epic Gaming Moments - Best Highlights Compilation',
    thumbnail: 'Exciting gaming action with colorful effects',
    channelName: 'Pro Gamer',
    channelId: 3,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel3',
    views: '2.3M views',
    uploaded: '3 days ago',
    duration: '18:45',
  },
  {
    id: 4,
    title: 'Travel Vlog: Exploring Beautiful Mountain Landscape',
    thumbnail: 'Stunning mountain scenery with sunset',
    channelName: 'Adventure Seeker',
    channelId: 4,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel4',
    views: '643k views',
    uploaded: '5 days ago',
    duration: '22:10',
  },
  {
    id: 5,
    title: 'Learn JavaScript in 2024 - Complete Beginner Guide',
    thumbnail: 'Code editor with JavaScript syntax highlighting',
    channelName: 'Code Academy',
    channelId: 5,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel5',
    views: '1.8M views',
    uploaded: '1 week ago',
    duration: '45:30',
  },
  {
    id: 6,
    title: 'Fitness Workout Routine - Get Fit in 20 Minutes Daily',
    thumbnail: 'Person doing workout exercises in modern gym',
    channelName: 'Fit Life',
    channelId: 6,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel6',
    views: '923k views',
    uploaded: '4 days ago',
    duration: '20:15',
  },
  {
    id: 7,
    title: 'Music Production Tutorial - Create Amazing Beats',
    thumbnail: 'Music production studio with equipment',
    channelName: 'Beat Maker',
    channelId: 7,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel7',
    views: '534k views',
    uploaded: '6 days ago',
    duration: '28:40',
  },
  {
    id: 8,
    title: 'DIY Home Improvement - Transform Your Space',
    thumbnail: 'Beautiful home interior renovation project',
    channelName: 'Home Pro',
    channelId: 8,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel8',
    views: '712k views',
    uploaded: '2 weeks ago',
    duration: '16:55',
  },
  {
    id: 9,
    title: 'Photography Tips - Capture Stunning Photos Like a Pro',
    thumbnail: 'Professional camera with beautiful landscape',
    channelName: 'Photo Expert',
    channelId: 9,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel9',
    views: '445k views',
    uploaded: '1 week ago',
    duration: '14:20',
  },
  {
    id: 10,
    title: 'Car Review 2024 - Latest Electric Vehicles Tested',
    thumbnail: 'Sleek electric car on scenic road',
    channelName: 'Auto Review',
    channelId: 10,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel10',
    views: '1.5M views',
    uploaded: '3 days ago',
    duration: '19:30',
  },
  {
    id: 11,
    title: 'Fashion Trends 2024 - Style Guide and Tips',
    thumbnail: 'Fashionable outfit display with accessories',
    channelName: 'Style Icon',
    channelId: 11,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel11',
    views: '67k views',
    uploaded: '5 days ago',
    duration: '11:45',
  },
  {
    id: 12,
    title: 'Science Explained - Fascinating Facts About Space',
    thumbnail: 'Beautiful space imagery with planets and stars',
    channelName: 'Science Hub',
    channelId: 12,
    channelAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=channel12',
    views: '892k views',
    uploaded: '1 week ago',
    duration: '25:10',
  }
];

export const mockComments = [
  {
    id: 1,
    author: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user1',
    text: 'This is absolutely amazing! Thanks for sharing this incredible content.',
    time: '2 hours ago',
    likes: 234,
  },
  {
    id: 2,
    author: 'Sarah Smith',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user2',
    text: 'Great video! Very informative and well-produced. Keep up the excellent work!',
    time: '5 hours ago',
    likes: 156,
  },
  {
    id: 3,
    author: 'Mike Johnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user3',
    text: 'I learned so much from this. Can you make more videos like this?',
    time: '1 day ago',
    likes: 89,
  },
  {
    id: 4,
    author: 'Emily Brown',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user4',
    text: 'Subscribed! This channel deserves way more recognition.',
    time: '2 days ago',
    likes: 312,
  }
];